### ISSUE TITLE
CORS support in sekai-res.dnaroma.eu?

### ISSUE THREAD

**Issue by Build774** [Sekai-World/sekai-viewer#21]
Is it possible to configure CORS for localhost (or all domains) on sekai-res.dnaroma.eu?
This can be helpful in local development.

**Comment by dnaroma** [comment]
can't add localhost as CORS domain to my cloud provider. I'm working on reverse proxy which is supported by `create-react-app`.

**Comment by dnaroma** [comment]
See https://github.com/Sekai-World/sekai-viewer/commit/686a98bca848292c807bc7828e951b514bc5ab61

**Comment by Build774** [comment]
It works great. Thanks!
