### ISSUE TITLE
Too many PRs by Transifex bot

### ISSUE THREAD

**Issue by Build774** [Sekai-World/sekai-viewer#220]
Currently transifex integration bot seems to open a PR each time the resource is changed.
It would be better to change the setting to something like opening a PR once a day (if possible).

**Comment by dnaroma** [comment]
yea I also found it's annoying, but transifex only provided another option to push the commit directly to repo. Can't control how it open PRs. Maybe I can open a branch for it and merge it when needed?

**Comment by Build774** [comment]
I think that's a good idea.
The problem is that the `main` branch and the branch for transifex have to be merged with each other.
Perhaps we should configure GitHub Actions to merge branches into each other on push.
(Just be careful to DO a fast-forward or it will create an infinite number of merge commits.)
Or maybe we can automate the merge just in the main to transifex direction.

**Comment by dnaroma** [comment]
> Or maybe we can automate the merge just in the `main` into transifex direction.

I think it's good. I prefer rebase which will make the tree clean.

**Comment by dnaroma** [comment]
Update: actions checkout only latest commit, it's quiet difficult to do rebase. Rebase manually and open a pull request - I think it's now the solution.
