### ISSUE TITLE
Camelcase suggestion 

### ISSUE THREAD

**Issue by iSwanGit** [Sekai-World/sekai-viewer#26]
There are some keys not using camelCase in json file of translation.
I found them when visited transifex, and these seem to be not consistent compared to others...

| | event.json | music.json |
| -- | :--- | :--- |
| Screenshot | ![image](https://user-images.githubusercontent.com/10243897/97032626-19183e00-159d-11eb-8239-e034cb2c2848.png) |  ![image](https://user-images.githubusercontent.com/10243897/97032574-043baa80-159d-11eb-9a59-00e8eb9a0c16.png) |
| key | already-ended | actual-playback-time |
| Suggestion | alreadyEnded | actualPlaybackTime |

**Comment by dnaroma** [comment]
I will fix it and on transifex as well.
