### ISSUE TITLE
[BUG] The width of the countdown flip card varies every second

### ISSUE THREAD

**Issue by iSwanGit** [Sekai-World/sekai-viewer#304]
**Describe the bug**

Countdown time cards flip normally, but its width are vary (not consistent)

**To Reproduce**
If you have macOS computer, you can find it at `Ongoing Event` in home page.

**Expected behavior**
Width of flip cards are consistent

**Screenshots**

https://user-images.githubusercontent.com/10243897/103435439-d71d0f80-4c51-11eb-85e4-669e9d5c2a37.mov

**Browser (please complete the following information):**
 - OS: macOS Mojave (10.14.6)
 - Browser: Chrome, Safari
 - Version:  87, 13.1

**Possible cause and/or solution**
Style of element class `flip-countdown` is defined like below.
```
font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif
```
It seems the fonts applied to different operating systems are different.
No problem has been found on Windows(Chrome).

I think the problem may be solved in the following way.
- Use the monospace font to be applied, regardless of the operating system
- Or assign and fix width of each flip card

**Comment by dnaroma** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The width of the countdown flip card varies every second](https://trello.com/c/DhEp4aEZ/50-the-width-of-the-countdown-flip-card-varies-every-second)
