### ISSUE TITLE
[BUG] flexbox displays not correctly on Safari

### ISSUE THREAD

**Issue by iSwanGit** [Sekai-World/sekai-viewer#305]
**Describe the bug**
Element which is used `display: flex` is shown its size wrong
Safari has a bug that can't inherit height in `flex`.

**To Reproduce**
1. Use Safari,
2. Go to `Ongoing Event` in home page
3. Change size of browser window
4. You can recognize the height of event banner is wrong

**Expected behavior**

Flexbox calculate height using width, keep original image ratio.

**Screenshots**

![image](https://user-images.githubusercontent.com/10243897/103435722-61677280-4c56-11eb-8ce2-772115d4688b.png)
![image](https://user-images.githubusercontent.com/10243897/103435723-67f5ea00-4c56-11eb-996c-7052413ccfcb.png)

**Browser (please complete the following information):**
 - OS: macOS Mojave (10.14.6)
 - Browser: Safari
 - Version: 13.1

**Possible cause and/or solution**
I don't know clear solution, it would be nice with someone's help

**Comment by dnaroma** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [flexbox displays not correctly on Safari](https://trello.com/c/BkQ5Z4xf/49-flexbox-displays-not-correctly-on-safari)
