### ISSUE TITLE
[BUG] Live2D low quality 

### ISSUE THREAD

**Issue by kogaoogami** [Sekai-World/sekai-viewer#314]
The zoom in/zoom out feature doesn’t work in the live2D. I’m not able to press the button. This causes the models to be low quality when I save them as images.

Browser I’m using is Safari 14.2

![BFAD7FF8-6D5E-4A2F-9148-81D3256135C0](https://user-images.githubusercontent.com/77634857/104945807-40f22480-5987-11eb-8f9e-abd5640c79d8.jpeg)

**Comment by dnaroma** [comment]
Hi kagaoogami,

can you upload one saved image? and that button is for fullscreen.

**Comment by kogaoogami** [comment]
![7D286E21-2988-48C4-80B5-CE2EACBA35F2](https://user-images.githubusercontent.com/77634857/104948274-0ab6a400-598b-11eb-8e43-9be9c5356437.png)

**Comment by dnaroma** [comment]
This image seems just normal, but the size of model is too small.

I need more information about your device. Please upload a full screenshot of https://www.mydevice.io/ on your device.

**Comment by kogaoogami** [comment]
![B0D57504-71EE-4C2E-8603-47643A8C4123](https://user-images.githubusercontent.com/77634857/104949619-3fc3f600-598d-11eb-9612-515e0eae087d.jpeg)
![2A7255C3-7699-4D8C-B149-14C320C15B76](https://user-images.githubusercontent.com/77634857/104949626-43577d00-598d-11eb-946f-eca989f0efae.jpeg)
![D7E85C35-259F-4B43-BF89-D949938FE450](https://user-images.githubusercontent.com/77634857/104949639-48b4c780-598d-11eb-9034-c1f4d7e83be1.jpeg)
![FA5C8B68-A878-425E-B04B-3EF25802B13F](https://user-images.githubusercontent.com/77634857/104949645-4bafb800-598d-11eb-967d-fc6d7e20b9e3.jpeg)
![177D6870-CC2D-420C-8378-42199E2B6C27](https://user-images.githubusercontent.com/77634857/104949653-4f433f00-598d-11eb-83fb-8245b4775a7a.jpeg)
![7F2BC2B7-0D28-4427-A8ED-2404099E3F9B](https://user-images.githubusercontent.com/77634857/104949657-510d0280-598d-11eb-855f-d40bbfa9576c.jpeg)
![B4FA7DEF-5D68-45F1-8842-CA2F5989F2E7](https://user-images.githubusercontent.com/77634857/104949690-5ec28800-598d-11eb-9271-1374621399b3.jpeg)
![EC1091DD-8571-4EF1-AECF-4F86D58C9EF6](https://user-images.githubusercontent.com/77634857/104949710-671ac300-598d-11eb-97f3-3f1c3a5ce54d.jpeg)

**Comment by dnaroma** [comment]
Thanks for the information. I will continue investigation.
