### ISSUE TITLE
[Feature request] Filter skill for card listing page

### ISSUE THREAD

**Issue by n3crosis** [Sekai-World/sekai-viewer#321]
**Motivation.**
Currently there's no skill filtering available in the card listing page, and I would like to filter cards by skill type.

**Related issue (if applicable)**
N/A

**Suggested Implementation**

Filter skills by four main types:

- スコアＵＰ
- 判定強化＆スコアＵＰ
- ライフ回復＆スコアＵＰ
- PERFECTのときのみスコアＵＰ

**Additional context**
I've implemented a sample filter function in my own fork, and could start a PR if this feature request is accepted.

**Comment by dnaroma** [comment]
Thanks, I'm looking forward to your PR 👍
