### ISSUE TITLE
[BUG] Cloud related functions seem broken

### ISSUE THREAD

**Issue by Subways-Sun** [Sekai-World/sekai-viewer#324]
Both saving teams and importing cards failed to complete. Not working on Safari (Ver 14) and Chrome (88.0) using macOS 11.2. Logged in via Twitter.
<img width="1536" alt="Screenshot 2021-02-06 at 20 43 52" src="https://user-images.githubusercontent.com/25404015/107118613-f1838200-68bc-11eb-9cd4-e589f7e5a55d.png">
<img width="1536" alt="Screenshot 2021-02-06 at 20 43 34" src="https://user-images.githubusercontent.com/25404015/107118614-f6483600-68bc-11eb-88a2-49f41b70d626.png">

**Comment by dnaroma** [comment]
Some settings are wrong. This bug is resolved.
