### ISSUE TITLE
[Feature request] Story Bgm

### ISSUE THREAD

**Issue by zib22** [Sekai-World/sekai-viewer#327]
**Motivation.**
Would like to listen to the game's bgm

**Related issue (if applicable)**
Would potentially like to hear other datamined audio files such as menu voice lines as well

**Suggested Implementation**
A new feature when you can listen to and download the game's Story and Menu bgm 

**Additional context**
The menu bgm for all Events is already available, so I assume this would be possible too. If not, I understand.

**Comment by LyingJay** [comment]
adding on to this request, i also want to hear other mp3 files that aren't bgm, such as sfx like the sound made when holding a golden hold note, or tapping a menu button

**Comment by dnaroma** [comment]
release 0.5.4
