### ISSUE TITLE
More filter and layout options for music, + misc

### ISSUE THREAD

**Issue by LyingJay** [Sekai-World/sekai-viewer#328]
**Motivation.**
The current filter and layout options feel very limited, making it harder to find music.
With the layout options, one lets me see 12 songs at a time with only the song name, image and MV types. The other lets me see 4 songs at a time and all the above information as well as the song difficulties. I feel as though the icon for the second layout suggests it is more compact, when it is not.
The filters only allow you to filter unit, MV (but only 1 type at a time) and sort the songs by date or ID. On the other hand, in the actual song details, there is more data that could be used to filter and identify songs.

**Related Issue**
- For filters in general, it is unclear whether they are AND, OR or XOR, and sometimes one type is wanted over the other, so maybe this could be added as an option?
- Make songs related to events link to the event they are related to. Also the same with cards, as it is strange that the event page links to event cards but not the other way round. Also if implementing songs linking to events, events should also link to songs.
- Some songs have incorrect Dance Members listed (e.g. Time Machine, only has three members but the 3DMV has five, Drop Pop Candy, and more)
- I believe all songs without a 3DMV have a Dancer Count stat when they should not have, while songs with 3DMVs show the dancers  so a dancer count stat is irrelevant (e.g. Hibana apparently has 3 dancers but it only has a 2DMV with two characters, Dappou Rock, Viva Happy, Next Nest and more)

**Suggested Implementation**
Song Filters
- Allow an AND type filter for MV Type. For example, a song with a 3DMV and 2DMV is Happy Synthesiser. Also, fix the issue with Viva Happy being classified as Static Image, as I believe Static Image implies a song has no other MV types available. Otherwise, every song would have Static Image as an MV type.
- Add an exclusive filter for all singers, and an exclusive filter for only virtual singers, and choose whether to search Sekai/Original/Solo versions. The first filter allows for users to find songs sung by specific characters or sets of characters. The second allows users to find songs sung by specific virtual singers, without including for example, all the songs involving Miku and sekai characters.
- Add a filter for composer, arranger and lyricist. This should probably be a dropdown.
- Add a filter for duration, where the user can input From time a To time b.
- Add a filter for level and (optional) difficulty, such that, for example, the user can find things like 1. All level 28 songs, or 2. All level 28 songs on Master difficulty.
- Add a filter for note count and (optional) difficulty, similar to duration input and level filter example.

Song Layout
- Allow for a new compact layout that displays the songs in rows, with small image on the far left, then song name, then difficulties and possibly other info, such as singers, mv types. As shown in the screenshot below.

**Additional context**
![image](https://user-images.githubusercontent.com/78644149/115024330-49fd7e00-9f03-11eb-8970-85f0e9528d3a.png)

Apologies if any of the issues I listed above in related issues or anywhere else in the post are already known issues. I can see there’s a lot of features coming up for Sekai viewer from the GitHub and trello, and I (and also the rest of the community, I’m pretty sure) really appreciate the hard work and effort put into this amazing project, and will continue supporting Sekai viewer!

**Comment by dnaroma** [comment]
> Also, fix the issue with Viva Happy being classified as Static Image, as I believe Static Image implies a song has no other MV types available. Otherwise, every song would have Static Image as an MV type.

The categories of a song is not determined by me. It is from game data.

> Make songs related to events link to the event they are related to

It requires extra work. Such information is not included in game data.

> Allow an AND type filter for MV Type.

I will make the MV type to be only AND type.

> Add a filter for duration

It was acquired from song mp3 file. Such filter will require external storage for song durations.

> Add a filter for note count

A little bit challenge.

Other requests, if possible, are accepted.

**Comment by dnaroma** [comment]
Mostly done in v0.5.0
