### ISSUE TITLE
Webp support for iOS <= 13 and macOS <= 11

### ISSUE THREAD

**Issue by dnaroma** [Sekai-World/sekai-viewer#33]
Polyfill with  [`webp-hero`](https://github.com/chase-moskal/webp-hero).

**Comment by Build774** [comment]
I was just wondering, isn't it possible to convert / process assets before they are uploaded?

**Comment by dnaroma** [comment]
> I was just wondering, isn't it possible to convert / process assets before they are uploaded?

Webp is smaller and thus better for network transmission.
Do you mean that providing png for browser without webp support?

**Comment by Build774** [comment]
Yes. May be there will be issues with storage and computing costs.
