### ISSUE TITLE
[Feature request] Card and Event details pages should link to their respective stories

### ISSUE THREAD

**Issue by alchzh** [Sekai-World/sekai-viewer#330]
**Motivation.**
It is unintuitive when looking for a card or event story text to go specifically to the story reader page and navigate to it (when we might already be on the card details or event details page).

It just makes sense.

**Suggested Implementation**
Have a link on the card and event details page to goes to the story reader like how its done on the member details page.

![image](https://user-images.githubusercontent.com/8976828/117577096-6762d980-b0b6-11eb-920c-22a655a595e2.png)

**Comment by dnaroma** [comment]
fixed in 0.5.3
