### ISSUE TITLE
[BUG] Regression: 17 digit IDs are detected as malformed

### ISSUE THREAD

**Issue by alchzh** [Sekai-World/sekai-viewer#332]
**Describe the bug**
bdf965b246184d14d8f748406745ee804b94287d assumes Sekai IDs are all 16 digits. Many users have 17 digit IDs as evidenced by my own account and others in friend code sharing channels (maybe newer accounts only?)

**To Reproduce**
1. Go to user homepage
2. Enter valid 17 digit id

**Expected behavior**
As before bdf965b246184d14d8f748406745ee804b94287d , it should be accepted and go through the regular verification process

(I went through the verification process once through fine before these changes were pushed as a result of the crashes I ran into)

**Screenshots**
![Screenshot showing my userid as `83508117668675584`, a 17 digit number](https://user-images.githubusercontent.com/8976828/117578039-7186d700-b0ba-11eb-8fbd-f85aa971555e.png)

_creating issue because more information is needed about what Sekai IDs are valid and not valid. A quick glance at the #friend-codes channel shows 16 and 17 digit IDs only, but I am unsure if this is generally true or if other ID lengths exist._

**Comment by dnaroma** [comment]
fixed in 0.5.3
