### ISSUE TITLE
[BUG] Live2D not adding new models

### ISSUE THREAD

**Issue by Racingtrio** [Sekai-World/sekai-viewer#339]
**Describe the bug**
 The new Live2D models of Kaito_band 
and sub_mafuyuchild not added. 

<

**Browser (please complete the following information):**
 - OS: Android 
 - Browser chrome
 - Version 0.6.0

**Possible cause and/or solution**
 Adding of live2D Models

**Comment by dnaroma** [comment]
should be fixed, if any problem, feel free to reopen it
