### ISSUE TITLE
[Feature request] Sekai User ID Can't Use In The Traditional Chinese Server

### ISSUE THREAD

**Issue by leoleetw** [Sekai-World/sekai-viewer#349]
Sekai User ID Can't Use In The Traditional Chinese Server
Alert "Sekai ID is the 16 digits number," but Traditional Chinese Server is 19 digits number

"Sekai Cards & Teams" can't save cards. (I don't connected to the account.)
![20211115](https://user-images.githubusercontent.com/10137244/141754452-76937a7e-6ee7-4cc0-aa66-30bee089c652.PNG)

**Comment by dnaroma** [comment]
As the announcement made when TC server is supported said, linking TC Sekai account will be supported later. Please wait for further announcements.
