### ISSUE TITLE
Pull Request Preview

### ISSUE THREAD

**Issue by Build774** [Sekai-World/sekai-viewer#35]
## Motivation

To allow reviewers review easily.
To allow contributors contribute easily.

## Demo

[This](https://github.com/Build774/sekai-viewer/pull/2) and [this](https://github.com/Build774/sekai-viewer/pull/3).  

Feel free to open PR in this repository.  
Your PR will be automatically deployed.

### GitHub repository for hosting PR builds (`<PR_REPO>`)

Must be public.  
Example: [`sekai-viewer-pr`](https://github.com/Build774/sekai-viewer-pr)

### Cloudflare Account

To uses Cloudflare Workers.  
The free plan will work fine.  

#### Cloudflare Worker

Create a worker with [this script](https://gist.github.com/Build774/88c45d0d61f0309d9460560fec2a649e) and set `PR_GITHUB_REPOSITORY` environment variable to `<OWNER_OF_PR_REPO>/<PR_REPO>`.

### Set Secrets to this GitHub repository

![Secrets](https://user-images.githubusercontent.com/73220460/97081895-7dd8a480-1640-11eb-8bb7-b5f7e641cf1f.png)

#### `PR_DEPLOY_ORIGIN`

Origin to deploy.  
Example: `https://sekai-viewer-pr.build774.workers.dev` (no trailing slash!)

#### `PR_GITHUB_TOKEN`

Personal Access Token which has `write` access to PR repository.

### Update GitHub Workflow file (pr.yml)

[Here](https://github.com/Build774/sekai-viewer/blob/main/.github/workflows/pr.yml).

## Security considerations

Any codes can run at `npm ci` and `npm run build`  
I think secrets and tokens are not available at that time, but I may be wrong since I'm new to GitHub Actions.

## Why this is not a PR

Because there are many steps outside of GitHub to configure this.

**Comment by dnaroma** [comment]
This is a really good job. I'm also considering these days how to publish pr for review.
I don't know if I understood the workflow, please check my list:

1. I have to open a public repo for PRs.
2. I should write a CloudFlare Worker with the example you give.
3. Set env for GitHub Actions. (GitHub Actions has your Personal Access Token as `GITHUB_TOKEN` in default)
4. Update workflow file.

My questions:
1. Is my list above correct?
2. I'm not familiar with Cloudflare worker, is the domain ending with `workers.dev` provided by cloudflare?

**Comment by Build774** [comment]
> 1. Is my list above correct?

Yes.
I used Personal Access Token to push to `PR_REPO` but maybe `GITHUB_TOKEN` will also work (not tested).

> 2. I'm not familiar with Cloudflare worker, is the domain ending with workers.dev provided by cloudflare?

Yes. `workers.dev` is Cloudflare's domain.  
You can take `<subdomain>.workers.dev` when activating a Cloudflare worker and can route any workers to `<subsubdomain>.<subdomain>.workers.dev`.

**Comment by dnaroma** [comment]
@Build774 I have deployed it.

**Comment by Build774** [comment]
Thanks. I'll open some PRs.
