### ISSUE TITLE
[BUG] Internal server error

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#350]
**Happened everytime i wanted to update my name, this is super annoying**

**To Reproduce**

**Screenshots**

![image](https://user-images.githubusercontent.com/94912171/143866511-07ea797c-fa34-4a47-92bb-3f735f3f36cc.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 0.9.6

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
Investigated, an DNS server error confirmed. Resolving...

**Comment by dnaroma** [comment]
I think it is resolved. If any problem, feel free to reopen it.
