### ISSUE TITLE
[Feature request] - collaboration with sekai song wishlist

### ISSUE THREAD

**Issue by TitusEfferian** [Sekai-World/sekai-viewer#356]
**Motivation.**
pjsekai brings back all the vocaloid fanbase from old generation and new generation. lot of vocaloid fanbase came from 2010 - 2012 era. And we have lot of old vocaloid song that we want to be playable on the pjsekai games. what if we create additional feature to sekai best that user can upload their wishlist song that still not available at the games, and let the community to take love votes to see how much our community wants that song to be available on the game, and hopefully sega can see this feature

**Suggested Implementation**
quick introduce about me, i am also a software engineer, and i have already create the end to end features for this "wishlist" that you can see here for demo https://sekai-wishlist-ikriwoqz2a-as.a.run.app

and i want to propose if we can collaborate together about this. 
for example, we can add additional menu in your sidebar called "song wishlist" and if the user clicked it, it will be redirect to my deployed service. maybe i can buy a domain "sekai-wishlist.xyz" or something

let me know what you think about this

thank you

**Comment by dnaroma** [comment]
This is a pretty good idea. I can add a wish list pointing to your service, and for convenience I may provide a subdomain like "wishlist.sekai.best" for your service if you will.

**Comment by TitusEfferian** [comment]
>and for convenience I may provide a subdomain like "wishlist.sekai.best" for your service if you will.
i will be very grateful for this

>For user authentication, as many users use social login onto sekai viewer, it is a little bit hard to integrate.
for social media auth, i can add additional login method facebook, and twitter
because under the hood i used firebase auth for this.
but because we are different service i think yes it's hard if we want to make one single login for both of us.

let me know what you think, or if we can talk more about this in discord, here is my discord id Titus Efferian#0847

**Comment by dnaroma** [comment]
Todo:

- [ ] Waiting for wishlist to be available
- [ ] Point subdomain to wishlist

**Comment by TitusEfferian** [comment]
https://github.com/Sekai-World/sekai-viewer/pull/359
