### ISSUE TITLE
[Feature request] Navigate from card detail pages to corresponding event pages

### ISSUE THREAD

**Issue by Phynon** [Sekai-World/sekai-viewer#361]
**Motivation.**

It is kind of inconvenient that users are not able to navigate from detail pages of event cards to the event detail pages of them, while they can navigate from events to card details. A two-way link might be better.

**Related issue (if applicable)**
None

**Suggested Implementation**
An additional entry in between **Attribute** and **Available From** with a link navigating to the correlating event detail page could be a viable implementation.
![image](https://user-images.githubusercontent.com/50860128/148485662-2bbc5d5d-c885-4873-a7bc-6457e4fe29fe.png)

**Additional context**

If my memory serves me correctly, a card detail object in cards.json does not have a key indicating the corresponding event. Another thing is that some cards are not related to any events. Maybe I should use eventCards.json to implement this?

**Comment by dnaroma** [comment]
It is possible to use `eventCards.json` to implement this. It links even id with card ids.
