### ISSUE TITLE
[BUG] Unable to update profile page

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#364]
**Describe the bug**
It happens to me when i wanted to update my profile.
I'm unable to upload my avatar and i could not change my username.
I couldn't update my SEKAI profile and it says "[mobx-state-tree] Cannot modify 'AnonymousModel@/user', the object is protected and can only be modified by using an action.".

**To Reproduce**
 [mobx-state-tree] Cannot modify 'AnonymousModel@/user', the object is protected and can only be modified by using an action./Failed to upload avatar!

**Expected behavior**
When i wanted to update my SEKAI profile or upload my avatar.

**Screenshots**
![image](https://user-images.githubusercontent.com/94912171/149644838-995dfaf6-acfa-4ed8-9f1b-7420bb7da73a.png)
![image](https://user-images.githubusercontent.com/94912171/149644851-7c419584-fbd8-4b0a-9b99-26f9f6af3bda.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 1.2.4

**Possible cause and/or solution**
Not sure

**Comment by dnaroma** [comment]
fixed in 1.2.5
