### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pasuparfait** [Sekai-World/sekai-viewer#372]
trained images are missing…? 
![807B14D9-BD6E-41A0-BC77-1158CD0E9992](https://user-images.githubusercontent.com/100387571/155622963-2cb8d5cb-30ff-41e6-a6de-3e4dbf756b22.png)
![6E40ACFF-795F-478D-9857-B31FBDD41B5F](https://user-images.githubusercontent.com/100387571/155622978-565e2471-d567-4f82-a29a-a30b5f78e7aa.png)

**Comment by BentleyBentayga** [comment]
same issue, this needs a fix

**Comment by dnaroma** [comment]
duplicated
