### ISSUE TITLE
Unable to preview most existing files

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#375]
**Describe the bug**
Unable to preview most existing audio or image files because it said "Resource requested is unreadable, please reduce your request rate", some files are still previewable.

**To Reproduce**

Not sure

**Screenshots**

![image](https://user-images.githubusercontent.com/94912171/159191955-e3ec1ab3-9c71-4bb6-8060-2bf2d962f076.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 99.0.4844.74

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
A storage node is failed. Waiting for the provider to fix it.

**Comment by dnaroma** [comment]
Now restoring backup data, will go back normal soon

**Comment by BentleyBentayga** [comment]
> Now restoring backup data, will go back normal soon

![image](https://user-images.githubusercontent.com/94912171/161215353-5f08942d-db13-40f2-8c38-805d5d812fa6.png)
The issue still persists when fixing the storage node failure

**Comment by dnaroma** [comment]
> 
> > Now restoring backup data, will go back normal soon
> 
> ![image](https://user-images.githubusercontent.com/94912171/161215353-5f08942d-db13-40f2-8c38-805d5d812fa6.png)
> The issue still persists when fixing the storage node failure

If you still see this page, it means that the restoring is not finished
