### ISSUE TITLE
Uploading an Avatar isn't working [BUG]

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#377]
**Describe the bug**
I was trying to upload an avatar but it failed to do that.

**Expected behavior**
When uploading from a blank avatar.

**Screenshots**
![image](https://user-images.githubusercontent.com/94912171/160025953-252e5e28-8449-44ac-94ab-b3f45b323c66.png)

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 99.0.4844.82

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
Storage node failure, duplicated with #375
