### ISSUE TITLE
Live 2d not working on Chrome 

### ISSUE THREAD

**Issue by Lacendy0621** [Sekai-World/sekai-viewer#378]
**Describe the bug**
The live 2d preview is not working

**Screenshots**
![image](https://user-images.githubusercontent.com/102400752/160224498-6eb561fa-83be-4b94-ac0a-4156e1976769.png)

**Browser (please complete the following information):**
 - Google Chrome
*One user with Edge suggested their page is working, while a few others with other browsers have the same problem here

**Comment by dnaroma** [comment]
Duplicated #375
