### ISSUE TITLE
[Question] Would you like to open the public api???

### ISSUE THREAD

**Issue by jarvis1801** [Sekai-World/sekai-viewer#380]
**Motivation.**
Would you like to open the public api???

**Comment by jarvis1801** [comment]
whole sekai best api database project
In fact, I would like to create an Android app and insert some Ad for it
Do you interest for the android app, we could corporate for it.

**Comment by dnaroma** [comment]
If you want game data, you can find them in repo sekai-master-db-diff, if you want to let user log in onto sekai best, please tell me, we can cooperate in creating an Android App.

**Comment by jarvis1801** [comment]
Oh, nice. Would you please tell me your communication account, such as Discord, Slack...etc
Let we have a discussion on this.

**Comment by jarvis1801** [comment]
Since sekai viewer using react can install app via chrome,
the development of android plan is closed.
Thank you.
