### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by akaen** [Sekai-World/sekai-viewer#383]
**Describe the bug**

1.5anniversary Card There is not picture 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 100.0.4896.60
**Possible cause and/or solution**

![Screenshot_20220402-162247_Chrome](https://user-images.githubusercontent.com/63594025/161374297-5628c983-bf87-484d-9c48-b63fd5555a0a.jpg)

**Comment by dnaroma** [comment]
No repost of closed and known issue, or you will get blocked.
