### ISSUE TITLE
[Feature request] Formatted .anim file, batch download

### ISSUE THREAD

**Issue by ShiinaRinne** [Sekai-World/sekai-viewer#384]
**Motivation.**

- A lot of .anim file cant directly used in UnityEngine
- Files can't be downloaded in a batch

**Additional context**

I find a way to extract .anim file for Unity, but I can't find a method to download all source file to test(Only have 2.87GB), can you share a copy for me?

**Comment by dnaroma** [comment]
The .anim files are formatted as JSON, not in the format of unity code.
