### ISSUE TITLE
Why is it taking a long time to load the music meta [BUG]

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#385]
**Describe the bug**
Trying to compare the notecount of Mopemope.

**To Reproduce**
Simply go to Music Meta, it'll take forever.

**Expected behavior**
I expected to find a notecount that is comparable with Mopemope but it loads forever.

**Screenshots**
![image](https://user-images.githubusercontent.com/94912171/164474775-7b27b6f2-4618-49e1-b95c-45f64c2d4b2e.png)

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 100.0.4896.127

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
Should be fixed, if any problem, feel free to reopen.
