### ISSUE TITLE
Updating event data doesn't work [BUG]

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#386]
**Describe the bug**
Tried to update the event record when it is over but didn't work, and its not updating,

**To Reproduce**
Go to your profile and simply click the update button.

**Expected behavior**
Not sure

**Screenshots**
![image](https://user-images.githubusercontent.com/94912171/165748079-796619dc-f61a-43e2-b13e-b3d797b9b67d.png)

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 100.0.4896.127

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
Which server is it
