### ISSUE TITLE
Sekai Wishlist STILL needs updating with new songs [BUG]

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#389]
**Describe the bug**
A few days the wishlist still DOES not have any new songs. I'm waiting for SOOOOOOOOOO long that desperately needed new wishlist songs.

**To Reproduce**
Simply head to Sekai Wishlist.

**Expected behavior**
Not sure, but wait for a very long time.

**Screenshots**
![image](https://user-images.githubusercontent.com/94912171/169223553-e2b25f06-d5d7-4814-84e8-b0d018d6ede6.png)

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 101.0.4951.67

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
@TitusEfferian
