### ISSUE TITLE
Unable to play stories [BUG]

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#396]
**Describe the bug**
Every story will load forever to add some text and some voices to play, making it impossible to read a story.

**To Reproduce**
1. Go to Story Reader
2. Click Text Only
3. And click any Story

**Screenshots**
![image](https://user-images.githubusercontent.com/94912171/174436765-f8d34d6b-a4bf-4768-949b-d5ebe32001e8.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 102.0.5005.115

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
Fixed, open if still problems
