### ISSUE TITLE
[BUG]Asset Viewer 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by hedw1gP** [Sekai-World/sekai-viewer#397]
**Describe the bug**

Items won't appear in file browser.

The bug occurs on Sekai Viewer 1.4.1 when using Firefox 101.0.1 and Google Chrome 102.0.5005.115.

Console outputs:

```
Access to XMLHttpRequest at 'https://minio.dnaroma.eu/sekai-assets/?list-type=2&delimiter=%2F&prefix=%2F&max-keys=500' from origin 'https://sekai.best' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**To Reproduce**

1. Go to 'sekai.best' with Latest Firefox/Chrome.
2. Click on 'Asset Viewer'
3. See error at Console. If on Firefox, error occurs immediately; If on Chrome, you might need to wait a while.

**Expected behavior**

File list would appear.

**Browser (please complete the following information):**

 - OS: Windows
 - Browser: Firefox/Chrome
 - Version: Firefox 101.0.1, Google Chrome 102.0.5005.115.
 - IP and CDN settings: `126.19.*.*`, settings show JP

**Possible cause and/or solution**

Check https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

**Comment by dnaroma** [comment]
Fixed, open if still problems
