### ISSUE TITLE
Can't upload any avatar images again [BUG]

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#398]
**Describe the bug**
Not sure but the picture become default, trying to upload causes an error, after this, my profile pic is still default. Help me.

**To Reproduce**
1. Simply go to your profile and upload your avatar.

**Screenshots**
![image](https://user-images.githubusercontent.com/94912171/174438288-a8eeba48-f81b-4659-9c27-c781ea69717b.png)

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 102.0.5005.115

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
Fixed, open if still problems
