### ISSUE TITLE
Please update Sekai Wishlist [Feature request]

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#401]
**Motivation.**
It has been a long time ago since the wishlist never updated, please update it.

**Additional context**
![image](https://user-images.githubusercontent.com/94912171/176317749-dfef080e-6a37-4f97-bc68-5d73abf87358.png)

**Comment by BentleyBentayga** [comment]
This has been a month SINCE IT NEVER UPDATED IT DESPERATELY NEED TO AD NEW SONGS

**Comment by dnaroma** [comment]
WISHLIST IS NOT MAINTAINED BY THIS ORG, IT IS AN EXTERNAL PROJECT

**Comment by dnaroma** [comment]
ANY ATTEMPT TO OPEN SUCH ISSUE WILL MAKE YOU BLOCKED
