### ISSUE TITLE
Please add new asset images and files [Feature request]

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#405]
**Motivation.**
After uploading assets, why not upload asset images and files?

**Suggested Implementation**
Not sure, but new images and files will be there.

**Comment by C0NS03L** [comment]
I'm pretty sure that they are normally uploaded together, There's just some unexpected problems with the recent asset uploading
![image](https://user-images.githubusercontent.com/58496201/176892886-d6c86819-41a8-434c-b218-cf6d98b3040a.png)
