### ISSUE TITLE
I can't update Sekai Profile [BUG]

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#406]
**Describe the bug**
This has happened again when i wanted to update my sekai profile, i tried on mobile to see if it works but no luck.

**To Reproduce**
Try to update your sekai profile.

**Expected behavior**
Idk but it is expected to get script errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/94912171/180135168-9cf25e24-bf86-4ade-808e-ecd7ec0af2fa.png)

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 103.0.5060.114a

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
Please check again and close it if fixed.
