### ISSUE TITLE
[BUG]Can't open picture

### ISSUE THREAD

**Issue by Hsuan0420** [Sekai-World/sekai-viewer#409]
**Describe the bug**
All images on the website cannot be opened and downloaded

**To Reproduce**
I have restarted the website on both my phone and computer, but still nothing.

**Screenshots**
![Screenshot_2022-08-07-14-16-50-44_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/110758788/183278181-35141768-705e-4404-8c2c-6d686810150a.jpg)

 - Windows 11&android 11
 - Browser :chrome

**Comment by jomin398** [comment]
It also can't play song....
Looks like maintenance time..
