### ISSUE TITLE
Profile and event data can't be updated [BUG]

### ISSUE THREAD

**Issue by BentleyBentayga** [Sekai-World/sekai-viewer#411]
**Describe the bug**
It happens to me whenever i wanted to update my profile.

**To Reproduce**
1. Go to your sekai profile
2. Update your event data or your sekai profile
3. Load for a LONG time to finish it not responds.
4. When it is unresponsive it gets an error while trying to update your profile or your event data

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/94912171/188247614-a7ad011b-f3f6-4505-9823-6d670a1a9c95.png)

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 105.0.5195.102

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
Tell which server next time!

**Comment by BentleyBentayga** [comment]
IT STILL HAPPENS TO ME EVEN WHEN ITS FIXED, I GOT THE 400 AND 404 ERRORS HELP ME
![image](https://user-images.githubusercontent.com/94912171/188271971-67a025e9-7e21-499b-bb4f-9c6108c9043d.png)
![image](https://user-images.githubusercontent.com/94912171/188271975-abe18e7f-73b5-4115-b33a-fb802815b0a0.png)

**Comment by BentleyBentayga** [comment]
this actually worked when i tried logging out and logging back into Sekai Viewer
![image](https://user-images.githubusercontent.com/94912171/188291607-b7462de3-1741-4acd-96ab-b17064f6f3d8.png)
