### ISSUE TITLE
Verification Email Error

### ISSUE THREAD

**Issue by putty174** [Sekai-World/sekai-viewer#412]
I made a new account, but an error occurred after hitting the submit button. I never got a verification email (not even in spam mail), and I have no way to resend the verification email.

**Comment by dnaroma** [comment]
Please verify if it is fixed and close this issue.

**Comment by putty174** [comment]
Tried it but still no email. I am using Chrome Autofill to fill in the fields.

I filled out normally, and pressed "Submit", but there was no confirmation popup or anything to say it was complete. The submit button disabled itself, and then reenabled itself.

I am registering with a Yahoo email address, should I use something else?

I noticed that I had a popup in the bottom left saying "A new version is available" Do I need to be on the latest version to send register an account?

**Comment by dnaroma** [comment]
I found one mistake in configuration and fixed that. You may try it again.

**Comment by dnaroma** [comment]
Also check your spam mailbox

**Comment by putty174** [comment]
It works, thanks for your help.

I updated to 1.5.1 before starting registration. I used Chrome Autofill to fill username and email. Submitted and saw a confirmation page. I have received the email in my spam folder.
