### ISSUE TITLE
Request to use the asset server in another project

### ISSUE THREAD

**Issue by BLACKujira** [Sekai-World/sekai-viewer#416]
I have made a toolbox for create derivative works of project sekai, and I want to add some features to quickly download the required assets from the Sekai Viewer. 
I think I would better to request to you first.
The added feature includes download all songs, cards, models, etc.
I am worried that this will have a bad impact on your server.

https://github.com/BLACKujira/SekaiTools
This is my project, I will not push code or release update have these features without your permission.

我制作了一个用于project sekai二次创作的工具箱，我想在其中加入一些从Sekai Viewer中快捷获取所需资源的功能。
我想先征得你们的同意。
这些功能中包括下载所有的歌曲、卡片、模型，我担心这会对你们的服务器造成不好的影响。

https://github.com/BLACKujira/SekaiTools
这是我的项目，在征得你们的同意之前、我不会发布包含这些功能的代码和更新。

**Comment by dnaroma** [comment]
Hi BLACKujira,

Thanks for your message. I need more details about your tool, like what does it do, which functions does it have, how does it look like (screenshots for example).

**Comment by BLACKujira** [comment]
This is "Cut-in Scene Editor", This is used to display Cutin voice using Story Reader style.
Users need to type original text and translations for each cut in dialogue, and add appropriate actions and expressions for the live2d model.
This requires cut in voices and live2d models to work.
![Cut_in_Scene_Editor](https://user-images.githubusercontent.com/71865985/192592432-af43eb4a-4f8f-4ddd-b271-52edf984c5ce.png)

This is "L2DAnimationPreviewGenerator", This is used to Generate preview for animations of live2d model.
![L2DAnimationPreviewGenerator](https://user-images.githubusercontent.com/71865985/192592620-cb4596a7-41bd-4b26-856c-76dcdfff6b53.png)
This video shows how the two modules mentioned above work
https://www.bilibili.com/video/BV13Z4y1d7nt

This is "KizunaSceneEditor", This is used to showcase the kizuna Title, And it includes the function of "CutinSceneEditor".
![KizunaSceneEditor](https://user-images.githubusercontent.com/71865985/192592803-7a47235f-969b-4e9c-b134-fd5caf42204a.png)
You can watch this demo video of this module
https://www.bilibili.com/video/BV1dr4y1H7sD

This is "SpineAnimationGIFGenerator". This tool contains some spine models.
This module allows you to select animations for these spine models and output them as GIF or PNG sequences.
![SpineAnimationGIFGenerator](https://user-images.githubusercontent.com/71865985/192592983-4246b7c2-2d14-4151-8e66-d8dde946c27c.png)

The next mentioned modules does not push code yet.
This module counts the number of times game characters mention each other.
![count](https://user-images.githubusercontent.com/71865985/192593209-48f37612-70e9-4c78-8a89-496c59dc3dd1.png)
The results of the statistics are also editable
![count1](https://user-images.githubusercontent.com/71865985/192593267-4e277366-0dd8-4a74-97a7-fa5cdc687e25.png)
Afterwards, you can also make a PowerPoint-style presentation video of the statistics
![count2](https://user-images.githubusercontent.com/71865985/192593359-72f451fa-26d7-4e1f-ab35-1f343e49c481.png)

In this module, you can use spine models to make a static scene, and the number, position, and animation of the models can also be modified
![spine](https://user-images.githubusercontent.com/71865985/192593488-0b433fbd-a426-4e9e-9d1d-d5dbe0a92cd2.png)
![spine1](https://user-images.githubusercontent.com/71865985/192593541-85cb95e2-fdb9-44b6-a885-835b19fa0eab.png)

This is the radio module, which receives live comments from the online live room and uses the comments to select the songs to be played. It also has functions such as show cards and query dialogues
![radio](https://user-images.githubusercontent.com/71865985/192593756-58bc7d47-5a2f-4787-bc79-a634dbd5d1b5.png)

The last is the feature I would like to request you to add, the downloader. To be honest, I've actually used this a few times
![download](https://user-images.githubusercontent.com/71865985/192593950-4048fc47-5da9-40ca-95cc-bafa4a44dd91.png)
![download1](https://user-images.githubusercontent.com/71865985/192593982-d560fc18-cab9-4dcf-b430-ad5317500979.png)

**Comment by dnaroma** [comment]
Very nice and promising tool, you may use resources from Sekai Viewer (please do not use address ending with myqcloud.com, that costs too much). If you need any help, DM me per Twitter, Discord or Email.
