### ISSUE TITLE
[BUG] redirection mistake

### ISSUE THREAD

**Issue by ka16003** [Sekai-World/sekai-viewer#418]
**Describe the bug**

Don't know if this is a bug or just the wrong redirection.
one of the stickers is in Japanese but it shows while choosing Chinese as the language.
Not only in the case of Rui, but many other characters have the same issue. 
if this happened, it is usually the 14th of stickers if arrange in alphabetic order.

**Screenshots**

<img width="1149" alt="截圖 2022-10-23 下午4 56 51" src="https://user-images.githubusercontent.com/37267024/197399242-182d0d9c-630e-4e9e-986f-744f9b2a10db.png">

**Comment by dnaroma** [comment]
Please check if this sticker is already in game and if this sticker is correct in game.

**Comment by dnaroma** [comment]
Resources updated, can you check again

**Comment by ka16003** [comment]
yes, fixed.
