### ISSUE TITLE
[BUG] sekai-viewer - No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by Stardusstt** [Sekai-World/sekai-viewer#424]
**Describe the bug**
sekai-viewer won't appear in browser.

**To Reproduce**
1. Go to 'sekai.best' with Latest Firefox/Chrome.
2. See error -->

**Expected behavior**
sekai.best would appear.

**Screenshots**
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/40061990/201459820-8ae1ab29-2974-4766-96a3-9be9ca6b0af6.png">

**Browser (please complete the following information):**
 - OS: windows 11 , android
 - Browser: chrome 109.0.5410.0  , chrome android 108.0.5359.38 , firefox android 107.0b6

**Possible cause and/or solution**
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

**Comment by EternalFlower** [comment]
I think it related to the API being down. When Strapi going down a few days ago, I also get CORS errors from calls to strapi. dnaroma also made a tweet that the API is being fixed, but it will take some time.

**Comment by EternalFlower** [comment]
The API is back up. The CORS should be gone for you. I already check on my side.
