### ISSUE TITLE
[BUG] Cannot verify pjsk account

### ISSUE THREAD

**Issue by Lapis0875** [Sekai-World/sekai-viewer#429]
When I try to bind my pjsk account, it constantly fails with following error.
![image](https://user-images.githubusercontent.com/44740173/212137000-d929780e-7a9b-490f-a1ff-ee84463f2e46.png)

**To Reproduce**
1. Login using discord
2. Go to user page
3. Click 'bind' button below the text 'Sekai Profile'
4. Input my pjsk account id
5. Write the generated token in my pjsk profile
6. Leave profile in game
7. Click 'Verify' button

**Expected behavior**
My pjsk account should be bound.

**Screenshots**
![image](https://user-images.githubusercontent.com/44740173/212136297-2aa398de-1af8-4553-be2f-b2df9541e9c6.png)
![image](https://user-images.githubusercontent.com/44740173/212136836-a4340360-10e4-4c63-9b4a-5b60458f0ffe.png)
![image](https://user-images.githubusercontent.com/44740173/212137774-36c01307-9442-49fb-982c-f795bd427eed.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser Whale (based on chromium)
 - Version 3.18.154.7

**Possible cause and/or solution**
![image](https://user-images.githubusercontent.com/44740173/212137291-9c2b7d17-76ce-465e-8709-ce1425095049.png)
I don't know how the api is implemented, so I could guess followings :
- api cannot retrieve text in my profile's textbox
- somehow verification token is expired

**Comment by BentleyBentayga** [comment]
same here, it's been happening to me for more than 7 days ago! i verified my global sekai ID in contrast to my JP one, which i did not verify my account but putted my token! please fix it!

**Comment by viebschiev** [comment]
yeah this is happening to me too, and im on ensekai

**Comment by ay589** [comment]
Any fix?

**Comment by sjkim04** [comment]
I'm also getting this error, but when I inspected the request it returned a 500 (Internal Server Error), which seems to be a server issue. Could you devs look into this?

**Comment by dnaroma** [comment]
duplicated #370
