### ISSUE TITLE
[BUG] Sekai profile cannot update when a custom profile is set

### ISSUE THREAD

**Issue by raspberryspider** [Sekai-World/sekai-viewer#431]
**Describe the bug**
Attempting to update Sekai Profile while a custom profile is set in-game (EN server, unsure if this happens on other servers) causes an error (screenshot attached).

**To Reproduce**
1. Log in and go to user page.
2. Click on "update sekai profile" button while a custom profile is set.
3. Wait, then error appears.
4. (After, remove custom profile to return to the default profile, then clicking "update sekai profile" works as expected.)

**Expected behavior**
Either for the profile (and character ranks, area items, etc.) to update, or a friendlier error message to display eg. "Failed to retrieve profile information, are you using a custom profile?"

**Screenshots**
![image](https://user-images.githubusercontent.com/67039218/212523939-f4f659ee-d441-4e23-8b35-b3a6954b8daf.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 108.0.2

**Comment by dnaroma** [comment]
custom profile page is ignored now.
