### ISSUE TITLE
[BUG] Cannot load new assets

### ISSUE THREAD

**Issue by niconicozha** [Sekai-World/sekai-viewer#435]
**Describe the bug**

The song 39 is released in Project Sekai recently but I can't see it at the website.

**To Reproduce**

**Expected behavior**

New assets are shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/107761924/224050030-f6f37f1a-31f7-4112-bf13-25743ccda705.png)

**Browser (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 111

**Possible cause and/or solution**

**Comment by niconicozha** [comment]
Is anybody here

**Comment by LazytownSpo666** [comment]
You might wanna have to wait (one week or two) for the maintainer of Sekai Viewer to give reply to you.

**Comment by xfl03** [comment]
<img width="1458" alt="Snipaste_2023-03-15_01-30-12" src="https://user-images.githubusercontent.com/3205159/225089196-791d750c-f16a-4773-bed7-992972006914.png">
Try to refresh the page without cache.
