### ISSUE TITLE
[BUG] Difficulty is not displayed correctly on any table of songs

### ISSUE THREAD

**Issue by defectivekidney** [Sekai-World/sekai-viewer#445]
### Bug
Difficulty is not displayed correctly on any table of songs so it is impossible to tell the difficulty

### Reproduce
1. Go to [sekai.best/music_meta](https://sekai.best/music_meta)
2. See difficulty cells

### Screenshot
On Mac & Opera GX Browser
![Screen Shot 2023-06-28 at 4 36 15 PM](https://github.com/Sekai-World/sekai-viewer/assets/138069800/dad1fd2b-b582-4702-b978-e9e9d54a5033)

**Comment by yhsanave** [comment]
Issue also applies to the tables in the event planner and song recommender. Initial changes made it so the colors display properly but the difficulty levels still aren't shown.
![image](https://github.com/Sekai-World/sekai-viewer/assets/7477322/e40e503c-8bcf-4a6c-a820-1005471c7e78)
![image](https://github.com/Sekai-World/sekai-viewer/assets/7477322/a4911ae0-6c22-4d4c-a7cf-7ba9d9c3c5e9)
