### ISSUE TITLE
[BUG] Linking profile to JP Sekai not functional

### ISSUE THREAD

**Issue by mayoi-ayase** [Sekai-World/sekai-viewer#447]
Seems that the issue has been fixed? My profile has loaded now :D 

<s>**Describe the bug**
Attempting to link profile to my JP Sekai account does not work, even if I have entered my ID and the token in the bio correctly it results in the "Failed to verify ownership, did you leave the profile panel to save?" error.

**To Reproduce**
1. Enter Project Sekai ID into Sekai Viewer account wth no linked ID
2. Enter token into Project Sekai profile bio, leave profile to save data. Ensure that the default profile is selected, rather than a custom profile.
3. Click verify button on Sekai Viewer account.

**Expected behavior**
 Account linking successfully

**Screenshots**
![SS1](https://github.com/Sekai-World/sekai-viewer/assets/118338842/a74b6320-afc4-4cfd-bda0-fecbf7756c01)
![IMG_3595](https://github.com/Sekai-World/sekai-viewer/assets/118338842/78940988-2acf-4205-a1ea-69b3c96ea422)
![IMG_3596](https://github.com/Sekai-World/sekai-viewer/assets/118338842/ae351786-c6f2-4bc8-b70e-cb4c16f26190)
![image](https://github.com/Sekai-World/sekai-viewer/assets/118338842/e1ba7d08-6d86-4a0d-91d4-bcf2f13ed57b)
(I reset my token after posting these screenshots.)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 117.0 
- Project Sekai Version 2.7.5.Luna, played on 11" iPad Pro gen 4, iPadOS version 16.</s>

**Comment by hatkidchan** [comment]
Happens on EN server as well, tried linking it twice (by unlinking it first), didn't work

**Comment by exlysia** [comment]
![image](https://github.com/Sekai-World/sekai-viewer/assets/118210930/44b09d5e-04b9-4125-85ef-ba7ace8f433c)
![Снимок экрана 2023-11-04 131129](https://github.com/Sekai-World/sekai-viewer/assets/118210930/aa3e804e-8eb0-4005-8516-14a0637e1094)
![image](https://github.com/Sekai-World/sekai-viewer/assets/118210930/f498d439-e7b0-413d-8e08-eb449c56ba52)

Verification occurs, information about the player is received, but still an error...

**Comment by rakuzen25** [comment]
This issue still hasn't seemed to be fixed now… Instead of the user data, I'm receiving a 500 error from the backend.

**Comment by hatkidchan** [comment]
Seems to be working on EN server at least, on Sekai Viewer 1.9.4
