### ISSUE TITLE
[BUG]Cannot Open Pages “music” on PC

### ISSUE THREAD

**Issue by DanielToyama** [Sekai-World/sekai-viewer#451]
**Describe the bug**

Cannot Open Pages “music” on PC,It's full of white and empty.

**To Reproduce**
1. Go to 'Homepage'
2. Click on ['music'](https://sekai.best/music)

**Screenshots**

![image](https://github.com/Sekai-World/sekai-viewer/assets/53430542/b8050124-eb29-4489-8edf-98a0ea5120bb)

**Browser (please complete the following information):**
 - OS: Windows NT 10.0; Win64; x64
 - Browser Edge 117.0.2045.60 | WebKit 537.36

**Possible cause and/or solution**

**Comment by DanielToyama** [comment]
![image](https://github.com/Sekai-World/sekai-viewer/assets/53430542/396d16d9-f8b7-4388-8169-b3b294735e6c)

**Comment by dnaroma** [comment]
Cannot reproduce

**Comment by DanielToyama** [comment]
I found that on my two computers, only win11 triggers this situation. Is it a compatibility issue with win11?

**Comment by dnaroma** [comment]
I thought it may be a cache issue, try to clear cache on your win 11 machine

**Comment by DanielToyama** [comment]
> I thought it may be a cache issue, try to clear cache on your win 11 machine

No. This problem occurred when my computer first used this page. And the same thing happened when I tried to open it with my newly installed Google Chrome. Clearing the cache doesn't help either.

**Comment by dnaroma** [comment]
Which server?

**Comment by DanielToyama** [comment]
> Which server?

only jp
