### ISSUE TITLE
[BUG] freezing at preparing model display

### ISSUE THREAD

**Issue by ghost** [Sekai-World/sekai-viewer#469]
**Describe the bug**
 a glitch that affects multiple people on a certain app (am i meant to respond to this?)

**To Reproduce**
 what does reproduce mean....?

**Expected behavior**
 ?

**Screenshots**
 

**Browser (please complete the following information):**
 - OS: [e.g. iOS] Android
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] the newest version right now

**Possible cause and/or solution**

wifi?

it keeps on getting stuck at 'preparing model display and won't load no matter what i do. i have great connection so i dont know why its happening or why it keeps on getting stuck.

![Screenshot_20240120_210411_Gallery](https://github.com/Sekai-World/sekai-viewer/assets/157248494/362a49f3-2271-43a4-9651-9affbaf8dfec)

**Comment by dnaroma** [comment]
Please check 1.9.3, if fixed you can close this issue
