### ISSUE TITLE
[BUG] Third Anniversary Title Screen Assets not displaying

### ISSUE THREAD

**Issue by Fentiao-Vermicelli** [Sekai-World/sekai-viewer#470]
**Describe the bug**
In:
https://sekai.best/asset_viewer/title_screen/anniversary_3rd_bg01_rip/movie/
https://sekai.best/asset_viewer/title_screen/anniversary_3rd_bg02_rip/movie/
https://sekai.best/asset_viewer/title_screen/anniversary_3rd_bg03_rip/movie/
https://sekai.best/asset_viewer/title_screen/anniversary_3rd_bg04_rip/movie/
https://sekai.best/asset_viewer/title_screen/anniversary_3rd_bg06_rip/movie/

The five mp4 files in these five links do not work, the videos are not loading.

**To Reproduce**
1. Go to Asset Viewer
2. Scroll down and find title_screen, then click in
3. Then find and click on anniversary_3rd_bg01_rip (repeat the previous step to find anniversary_3rd_bg02_rip, anniversary_3rd_bg03_rip, anniversary_3rd_bg04_rip, and anniversary_3rd_bg06_rip)
4. Then click on movie
5. Then you'll see 3rd_anv_title_01.mp4, which had a broken file. (same with 3rd_anv_title_02.mp4, 3rd_anv_title_03.mp4, 3rd_anv_title_04.mp4, and 3rd_anv_title_06.mp4)

**Expected behavior**
After I click on the mp4 file, it should show a video of the third anniversary title screen of the matching character, just like the ones showing in https://sekai.best/asset_viewer/title_screen/anniversary_3rd_bg07_rip/movie/ and https://sekai.best/asset_viewer/title_screen/anniversary_3rd_bg05_rip/movie/

**Screenshots**
File that didn't work
![image](https://github.com/Sekai-World/sekai-viewer/assets/134884275/2d0fef2c-6c22-4c8c-acde-a0e2434e8335)

File that works
![image](https://github.com/Sekai-World/sekai-viewer/assets/134884275/95ed619e-8804-4a6d-9880-3dd4c0230e4d)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 120.0.6099.225

**Possible cause and/or solution**
Could be broken file, if possible, please upload it again

**Comment by HinataKato** [comment]
https://github.com/Sekai-World/sekai-viewer/assets/57648531/879f3cc6-125b-4397-a899-ccc3c93d6772

Some asset's H264 stream looks fine, like 3rd_anv_title_03.mp4 on the top (ffmpeg saying moov atom not found;fixed it with untrunc); some are just empty file

**Comment by dnaroma** [comment]
I guess network became unstable during upload, and some mp4 files are not correctly encoded. I'm re-encoding affected files and uploading them.

**Comment by Fentiao-Vermicelli** [comment]
> VID_20240128_111006_376.mp4 
> Some asset's H264 stream looks fine, like 3rd_anv_title_03.mp4 on the top (ffmpeg saying moov atom not found;fixed it with untrunc); some are just empty file

Ohhh so that's the issue, thank you for pointing that out

**Comment by Fentiao-Vermicelli** [comment]
> I guess network became unstable during upload, and some mp4 files are not correctly encoded. I'm re-encoding affected files and uploading them.

Ohhh, thank you so much for fixing them

**Comment by LazytownSpo666** [comment]
For me, it wasn't fixed.

**Comment by dnaroma** [comment]
> For me, it wasn't fixed.

@LazytownSpo666 can you provide more details? Just "not fixed" is not enough to know what's happening. I have uploaded them.
