### ISSUE TITLE
[BUG] Can't bind the account at TW server

### ISSUE THREAD

**Issue by Neko-no-akuma-TW** [Sekai-World/sekai-viewer#472]
**Describe the bug**

I want to bind my Sekai account to my sekai viewer account, but I can't.

**To Reproduce**

1. Go to Account Page
2. Enter the ID in Sekai
3. Run the verify process

**Expected behavior**

Verify Successfully

**Screenshots**

Nope

**Browser (please complete the following information):**
 - OS: iOS, Windows
 - Browser Safari, Edge
 - Version 0.6.0

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
Insufficient information. Did you enabled custom profile? If yes, you can try to verify with normal profile.

**Comment by Neko-no-akuma-TW** [comment]
> Insufficient information. Did you enabled custom profile? If yes, you can try to verify with normal profile.

I used normal profile to verify, but it didn't work.

**Comment by dnaroma** [comment]
What's your username on sekai viewer

**Comment by dnaroma** [comment]
It should be fixed, please test again

**Comment by Neko-no-akuma-TW** [comment]
> It should be fixed, please test again

OK, by the way, does this change update to https://sekai.best ?

**Comment by dnaroma** [comment]
> > It should be fixed, please test again
> 
> OK, by the way, does this change update to https://sekai.best ?

Sorry what do you mean?

**Comment by Neko-no-akuma-TW** [comment]
> > > It should be fixed, please test again
> > 
> > OK, by the way, does this change update to https://sekai.best ?
> 
> Sorry what do you mean?

Uhh, I mean does the official site update this change?
