### ISSUE TITLE
[Feature request]可以让资产管理器有复选框，可以批量下载咩？

### ISSUE THREAD

**Issue by RE-TikaRa** [Sekai-World/sekai-viewer#479]
在资产管理器下载数据的时候，只能一个一个点，可以的话能不能有复选框和多文件打包下载呢？这样的话方便很多，然后可以的话麻烦请出一个游戏原始数据的资产管理器，因为想要看看他是如何加密的，想要自己试试看处理数据。麻烦了！！

**Comment by dnaroma** [comment]
Do it yourself
