### ISSUE TITLE
[Feature request] the ability to search.

### ISSUE THREAD

**Issue by nobodyF34R** [Sekai-World/sekai-viewer#480]
**Motivation.**
It is very challenging to locate specific content within the platform efficiently. Implementing a search feature would greatly enhance user experience by enabling quick and targeted access to desired information.

**Related issue (if applicable)**
N/A

**Suggested Implementation**
Integrate a search bar prominently within the platform interface, allowing users to input keywords or phrases. Upon submission, display relevant results sorted by relevance, date, or other criteria. Implement filters or advanced search options to refine results further.

**Additional context**
Due to the way the website's data is loaded, it is impossible to ctrl+f to search. A built-in search bar is crucial for a site like this which contains large volumes of information.

**Comment by dnaroma** [comment]
Please open a discussion for it, and give more definition like what could searched, keywords etc.
