### ISSUE TITLE
[BUG] missing live2d models

### ISSUE THREAD

**Issue by yoshakami** [Sekai-World/sekai-viewer#489]
**Describe the bug**

When loading any model of this list below, the UI gets stuck on "Loading model motions..."
<br>

**To Reproduce**
1. Go to https://sekai.best/l2d
2. Click on the dropdown menu 
3. Select any model of the list below
4. Click on show
5. see error on the console:
```
GET https://storage.sekai.best/sekai-assets/live2d/motion/02saki__motion_base_rip/BuildMotionData.json 404 (Not Found)
Live2D-CrAPW7OD.js:37 Uncaught (in promise) wt {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
```
<br>

**full list of not working live2d models**
```
02saki_black
03honami_black
04shiho_black
06haruka_black
09kohane_longunit_black
09kohane_unit_black
10an_black
11akito_black
12touya_black
13tsukasa_cloth01black
17kanade_black
18mafuyu_black
19ena_black
20mizuki_black
21miku_bandblack
21miku_idolblack
21miku_normalblack
21miku_streetblack
22rin_normalblack
26kaito_idolblack
26kaito_normalblack
sub_anfather_black
sub_aratablack02
sub_bakunoreki_black
sub_cordnukio_black
sub_mikudayoteacher_black
sub_mrmrhouse_landlord
sub_nagi_black
sub_otoribrother2_black
sub_partner_black
sub_riho_black
sub_tatsuya_black
v2_06haruka_casual_black
v2_17kanade_casualblack
v2_26kaito_normalblack
```

<br>

**Expected behavior**
It should load the live2d model, all other models work fine

<br>

**Screenshots**

![image](https://github.com/Sekai-World/sekai-viewer/assets/62856297/20c4e1ba-2afe-4abb-84c3-2f750cd7abec)

<br>

**Browser (please complete the following information):**
 - OS: Windows 10 & Android 13
 - Browser Chrome & Firefox
 - Version (latest)
<br>

**Possible cause and/or solution**

missing assets? or an oversight maybe

**Comment by dnaroma** [comment]
no proper motion file found for `sub_mrmrhouse_landlord`, still invesgating

**Comment by yoshakami** [comment]
thank you for the fix!
in case you would like to know which ones are still not loading, it's those 2:
```
sub_aratablack02
sub_mrmrhouse_landlord
```

**Comment by dnaroma** [comment]
> thank you for the fix!
> 
> in case you would like to know which ones are still not loading, it's those 2:
> 
> ```
> 
> sub_aratablack02
> 
> sub_mrmrhouse_landlord
> 
> ```
They need some special processing, will get fixed later!
