### ISSUE TITLE
Regarding the website

### ISSUE THREAD

**Issue by LazytownSpo666** [Sekai-World/sekai-viewer#493]
Here are the issues related the website:

1. Some assets were not added, or removed (e.g. Chibi-related assets, Mid-gameplay voice audio (don't know what it is), Gacha phrase audio for some cards).
2. Twitter (currently X) & Discord icons were outdated and are not to be used anymore.

**Comment by dnaroma** [comment]
1. Can you tell some example of which assets are missing?
2. Icons will be updated

**Comment by LazytownSpo666** [comment]
1: Examples are:
- Chibi-related assets
- Audio files of characters talking mid-gameplay
- Gacha phrase audio for some cards

2: When?

**Comment by LazytownSpo666** [comment]
Hello?! are you replying to the comment???

**Comment by dnaroma** [comment]
1. You can find most of them in Asset Viewer, if not, that means it is not planned yet.

2. No ETA
