### ISSUE TITLE
[BUG] with the live2d models!

### ISSUE THREAD

**Issue by Kitkatkoi** [Sekai-World/sekai-viewer#495]
**Describe the bug**
<!-- the models aren’t working they’re only doing the hand poses
I have photo proof of it!
![IMG_5899](https://github.com/Sekai-World/sekai-viewer/assets/171430709/42bb2862-2bd9-4c1a-9735-95b0285a6081)
![IMG_5898](https://github.com/Sekai-World/sekai-viewer/assets/171430709/2ddbb793-a8dc-4757-af9f-234c87fb33da)
![IMG_5897](https://github.com/Sekai-World/sekai-viewer/assets/171430709/05603c85-1a66-4d01-b683-387b9363f55e)
![IMG_5896](https://github.com/Sekai-World/sekai-viewer/assets/171430709/91197e3b-9e1f-448a-9ef6-067955b29d40)
![IMG_5895](https://github.com/Sekai-World/sekai-viewer/assets/171430709/f57669fb-51a6-4532-a036-543fa1aa0280)

**Comment by LazytownSpo666** [comment]
Lack of description, reproduction steps, etc.

**Comment by dnaroma** [comment]
Please add details otherwise it will be closed.

**Comment by LazytownSpo666** [comment]
You should close this issue as not planned instead of completed.

**Comment by dnaroma** [comment]
> You should close this issue as not planned instead of completed.

Thanks, already closed as not planned
