### ISSUE TITLE
Regarding Event Analyzer

### ISSUE THREAD

**Issue by LazytownSpo666** [Sekai-World/sekai-viewer#497]
Hi there. I would like to access the Event Analyzer feature in Sekai Viewer, but it's not accessible as the button is greyed out. Am i not allowed to use it, or is the feature incomplete?

**Comment by dnaroma** [comment]
It is incomplete so not available

**Comment by LazytownSpo666** [comment]
If it's unavailable, can i have a preview of Event Analyzer right now?

**Comment by dnaroma** [comment]
No preview either. If you are a Patron with high payouts, I will develop a preview ASAP.
