### ISSUE TITLE
[BUG] when downloading on IPhone the models are glitchy/blurry.

### ISSUE THREAD

**Issue by Kitkatkoi** [Sekai-World/sekai-viewer#499]
When you download the Live 2D model of any character in an iPhone, it’s happening to me the models mouth is a green like about two dots and it’s extremely blurry/buggy like, downloaded photos with normal Ichika and culture emu,
Please fix this as soon as possible! :)
![download 8](https://github.com/Sekai-World/sekai-viewer/assets/171430709/6d00ff0c-c65b-49a0-84b7-706b81489e94)
![download 9](https://github.com/Sekai-World/sekai-viewer/assets/171430709/14f11620-c5ff-43d6-a022-ff0dba416fe9)

**Comment by dnaroma** [comment]
I can't see anything abnormal on my iPhone.

**Comment by dnaroma** [comment]
The downloaded photo is blurry because of downsampling, I will try to figure out this.

**Comment by Kitkatkoi** [comment]
> The downloaded photo is blurry because of downsampling, I will try to figure out this.

Alright thank you! :)

**Comment by Kitkatkoi** [comment]
From the current update they’re fixed now thank you! :)
