### ISSUE TITLE
Missing Song Data

### ISSUE THREAD

**Issue by alciee** [Sekai-World/sekai-viewer#500]
Two new songs that were EN server exclusive were recently added to TW and KR servers (sweety glitch and Hello Builder). I was hoping the data for these songs could be added to the event planner and song recommender. Thanks!

**Comment by dnaroma** [comment]
EN server will be updated before tomorrow

**Comment by alciee** [comment]
tysm!

**Comment by dnaroma** [comment]
please check current state and close this issue if fixed

**Comment by alciee** [comment]
still not fixed

**Comment by dnaroma** [comment]
Thanks for checking, I will let it update again

**Comment by dnaroma** [comment]
No more updates can be found, can you specify which songs are missing?

**Comment by alciee** [comment]
sweety glitch and Hello Builder

**Comment by dnaroma** [comment]
> sweety glitch and Hello Builder

they will be marked as exclusive songs for en server. as a temporary solution, you can listen them on kr and tc server which are the same.

**Comment by alciee** [comment]
But they still aren't available in the event planner for any server

**Comment by dnaroma** [comment]
They won't cause of lack of related data analysis
