### ISSUE TITLE
Missing Post 3rd Anni Card Cutouts In Asset Viewer

### ISSUE THREAD

**Issue by PeachyOranges** [Sekai-World/sekai-viewer#508]
A While Back You Could Find The Post 3rd Anni Skill Card Cutouts In The Asset Viewer But I Guess Changes To The Depository Makes Then Unable To Be Viewed Anymore.

**Comment by LazytownSpo666** [comment]
1: Bad grammar

2: The owner of this repository is offline and won't respond to you, at least until further notice (a long time lol).

**Comment by dnaroma** [comment]
The game dev decided not to make any card cutouts anymore.
