### ISSUE TITLE
[BUG]Mizuki's missing neck and lower body.

### ISSUE THREAD

**Issue by honeming** [Sekai-World/sekai-viewer#510]
**Describe the bug**
The Live2D model `20mizuki_culture` is missing its neck and its lower body in sekai viewer and downloaded image

**To Reproduce**

**Screenshots**
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/4939e6b3-8e04-4ca6-b8e7-d3f8a6c74aee">
Downloaded image
![20mizuki_culture-2024-07-26](https://github.com/user-attachments/assets/25a7a7e2-642d-4bd9-8d3b-38ac49b31c6c)

**Browser (please complete the following information):**
 - OS: macOS Sequoia Beta 4
 - Browser: Arc(Chromium)
 - Version: 1.52.0(126.0.6478.183)

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
please search before opening a new issue
