### ISSUE TITLE
[Feature request] Adding Titles for Trust Rank

### ISSUE THREAD

**Issue by Dawnstar10K** [Sekai-World/sekai-viewer#513]
I was trying to work on building a chart for my character and trust rankings so I can keep track of them and I realized there's no images up for the trust rank titles. I love this website for getting the photos I need as most databases use WEBP files for photos not allowing just the photos to be downloaded as png/jpeg.

**Comment by dnaroma** [comment]
Most webp files have corresponding png files, just change the extension

**Comment by dnaroma** [comment]
Will be released soon.
