### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aliicexq** [Sekai-World/sekai-viewer#514]
**LIVE2D**I'm not sure if it's my connection's fault , but whenever I go on the LIVE2D and try to show a model , all it says is "no options" ; therefore , i cannot download or show them

**To Reproduce**
1. Go to 'The three dots up'
2. Click on 'LIVE2D'
3. Type in model
4. See error -->

**Expected behavior* 
seeing the model's names like before , for example "mizuki_normal001". 

**Screenshots**

**Browser (please complete the following information):**
 - OS: [Android]
 - Browser [chrome]
 - Version [1.1.12]

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
See announcements on discord or twitter
