### ISSUE TITLE
Downloading LIVE2D model

### ISSUE THREAD

**Issue by Aliicexq** [Sekai-World/sekai-viewer#515]
**Describe the bug**
whenever I try to download a LIVE2D model , everytime , after downloading one after I click to download another one nothing happens. 

**To Reproduce**
1. Go to 'live2d'
2. Download a model
3. Costumize another time your model and try to download it.
4. See Error -->

**Expected behavior**
I expected it to download normally without having to restart the whole website.

**Screenshots**

**Browser (please complete the following information):**
 - OS: ANDROID 
 - Browser chrome 
 - Version latest version

**Possible cause and/or solution**

**Comment by dnaroma** [comment]
Cannot reproduce

**Comment by LazytownSpo666** [comment]
I apologize but, i can't reproduce your issue. I tried reproducing, and the download function is still working even after switching to another model several times.
