### ISSUE TITLE
[BUG] mizuki's neck and legs missing

### ISSUE THREAD

**Issue by ririimiya** [Sekai-World/sekai-viewer#517]
**Describe the bug**
so when i was trying out mizuki's models, i noticed her legs and neck were missing. i did try refreshing the page and switching models, but they didn't work. motions and expressions worked fine however

**To Reproduce**
<!-- Steps to reproduce the behavior:
1. click on 'Live2D' on sekai.best
2. use model '20mizuki_culture'

[**Screenshots**](https://paste.pics/c7604c77576ceb4ef82523a0ee4e3da6)

**Browser (please complete the following information):**
chrome

**Comment by dnaroma** [comment]
Please describe the model name and add screenshots of possible
