### ISSUE TITLE
[BUG] live 2D models have been removed?

### ISSUE THREAD

**Issue by Sayayiyi** [Sekai-World/sekai-viewer#518]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**
 - OS: iOS 
 - Browser: Google Chrome

**Comment by LazytownSpo666** [comment]
You didn't even provide the description of the issue, steps to reproduce, expectation of behavior, nor even screenshots.

Please provide them, otherwise it will be closed.
