### ISSUE TITLE
[Feature request] Adding Alt Hair To Live2D?

### ISSUE THREAD

**Issue by Dawnstar10K** [Sekai-World/sekai-viewer#520]
I know this is probably a long shot but it'd be really really cool if we could see the alt hairstyles from Lim/ColorFes/BloomFes cards on the Live2D models. It'd make it so much simpler to try and get a similar vibe hairstyle than their default for doing art with the 2D models. Being a beginner artist is a struggle lol.

I think maybe there could be a setting like the apply model pose and apply model expression but for the hair, which could be converted from the 3D models perhaps? Again I totally understand if this is impossible or incredibly difficult but it'd be really awesome and cool!

**Comment by dnaroma** [comment]
You can edit model in Live2D editor, Sekai Viewer can't do this. If you are interested and want to give some help please feel free to contact me.

**Comment by Dawnstar10K** [comment]
@dnaroma I don't know how to model edit sadly, I don't think I could be of help with that
