### ISSUE TITLE
[BUG] Incorrect timezone and... Happy 2nd Anniversary?

### ISSUE THREAD

**Issue by MinatoIsuki** [Sekai-World/sekai-viewer#521]
**Describe the bug**
Global version of the game uses PDT timezone, but the website uses the device local timezone instead.

For me, 10pm at Sep.29 (PDT) (or 5am at Sep.30 in UTC) should be 12pm at Sep.30 (UTC + 7).
But, at 10pm Sep.29 (UTC + 7) the countdown is over and the message "Happy 4th Anniversary!" is displayed.

Also, the image/banner is saying "Happy 2nd Anniversary!", it should be the 4th.

**To Reproduce**
Just go to https://sekai.best/.
Do note that you will have to set your clock forward for this bug. (if only your clock is behind 10pm, it doesn't matter which timezone)

**Expected behavior**
At 10:10pm, the timer should display `00:13:50:00`.

**Screenshots**
Time is at 9:13pm Sep.29 (UTC + 7) in this screenshot.
![image](https://github.com/user-attachments/assets/fe2338c4-7efb-4534-887c-5a55e7dfd4f1)

Time is at 10pm Sep.29 (UTC + 7) in this screenshot.
![image](https://github.com/user-attachments/assets/d09cfd86-21de-4849-aa67-272ba2e02e4c)

**Browser (please complete the following information):**
 - OS: Linux Mint 21.3 x86_64 
 - Browser: Brave
 - Version: Brave v1.69.160 | Chromium v128.0.6613.114 

**Possible cause and/or solution**
- Incorrect timezone in the timer, you can convert system time to PDT time for better measurement.
- The banner can be fix by modifying the "2nd" to the "4th", or use JP 3rd Anniversary (without text, if applicable)

**Comment by dnaroma** [comment]
the banner is deprecated, will make a new one
