### ISSUE TITLE
[BUG] Can't Download Card Thumbnails

### ISSUE THREAD

**Issue by Dawnstar10K** [Sekai-World/sekai-viewer#523]
**Describe the bug**
I'm trying to make a card tracker for myself and I noticed here on Sekai Best that when you go to download the thumbnails it only downloads the border? Not the card and border. And I can't use just the full card art because it's too big.

**To Reproduce**
<!-- Steps to reproduce the behavior:
1. Go to, say, Ichika's 1 star card.
2. Right click and do either save image or open image in a new tab
3. Either see the image in new tab being just the card border, or see it in the files as such.
![Untitled](https://github.com/user-attachments/assets/29b168cf-f1eb-4b53-82b8-ff04cc38e31e)

 - OS: [e.g. iOS] Windows 11 Home
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] Version 131.0 (64-bit)

Thank you in advance for any suggestions or fixes!

**Comment by R-data91** [comment]
You must combine the frame, rarity icon, and card icon image to create a single card.
Card icon can be viewed in [Asset Viewer](https://sekai.best/asset_viewer/thumbnail/chara_rip/)

**Comment by Dawnstar10K** [comment]
I don't know how I'd combine all the pieces together... is there no way to make it possible for users to just download the complete file? I'm sorry I'm just frustrated

**Comment by R-data91** [comment]
At least from what I know, There is no way to do this with the sekai viewer.
If you don't want to try the combination method, you might want to check out [wiki](https://www.sekaipedia.org/wiki/List_of_cards) (but with a mix of old and new formats).

**Comment by Dawnstar10K** [comment]
Thank you anyway I figured out that I can use Sekaipedia and convert from WebP to PNG
