### ISSUE TITLE
[BUG] Sekai Viewer Music tab not responding on iphone even though on strong internet

### ISSUE THREAD

**Issue by yayicanfart** [Sekai-World/sekai-viewer#524]
The Music Tab wont load on iPhone

**To Reproduce**
1. Go to 'sekai.best (on mobile)'
2. Click on 'Music'

**covers, info, more not loading**

**Browser:**
 - OS: [iOS]
 - Browser [Google]
 - Version [340.3]

**Comment by dnaroma** [comment]
Please scroll down a little bit, it will load. This will get fixed.

**Comment by dnaroma** [comment]
fixed in 1.12.6
