### ISSUE TITLE
[BUG] Saki’s waist is missing?

### ISSUE THREAD

**Issue by Timathesilly** [Sekai-World/sekai-viewer#527]
**Describe the bug**
On Saki’s Live 2D model, when you download images of it, her waist is just transparent.

**To Reproduce**
1. Go to 'Live 2D'
2. Click on ‘Model'
3. Scroll down to '002Saki_Cloth001'
4. Click on 'Save Image '
5. Check the saved image
6. See error 

**Expected behavior**
 I expected her model to appear how it’s supposed to - with her waist still present.

**Screenshots**

![IMG_2610](https://github.com/user-attachments/assets/ec0eaab9-c757-4dbf-b0cd-b7216a86659b)

**Browser (please complete the following information):**
 - OS: [IpadOS 17.6.1]
 - Browser [Safari]
 - Version [1.12.6]

**Possible cause and/or solution**
No idea since I don’t really know how this stuff works - sorry!

**Comment by dnaroma** [comment]
#506
